// Database Kosakata SKD TIU (Diekstrak dari PDF yang diunggah)
const dbWords = [
    { word: "AFIRMASI", synonym: "Penegasan, peneguhan", level: "Menengah" },
    { word: "AGITASI", synonym: "Persuasi, ajakan", level: "Sulit" },
    { word: "AGRARIA", synonym: "Pertanahan", level: "Mudah" },
    { word: "AGRESI", synonym: "Serangan, penyerangan", level: "Mudah" },
    { word: "AGUNAN", synonym: "Jaminan", level: "Menengah" },
    { word: "AJUN", synonym: "Ajudan, asisten", level: "Sulit" },
    { word: "AKREDITASI", synonym: "Pengakuan", level: "Mudah" },
    { word: "AKSELERASI", synonym: "Percepatan", level: "Menengah" },
    { word: "AKSEPTOR", synonym: "Penerima", level: "Sulit" },
    { word: "AKTUAL", synonym: "Nyata, anyar", level: "Menengah" },
    { word: "AKURASI", synonym: "Ketelitian", level: "Mudah" },
    { word: "AKURAT", synonym: "Benar, jitu, saksama", level: "Mudah" },
    { word: "ALEGORI", synonym: "Kias", level: "Sulit" },
    { word: "ALGORITMA", synonym: "Prosedur pemecahan", level: "Menengah" },
    { word: "ALIANSI", synonym: "Afiliasi, asosiasi", level: "Menengah" },
    { word: "ALTERNATIF", synonym: "Cara lain", level: "Mudah" },
    { word: "AMATIR", synonym: "Pemula", level: "Mudah" },
    { word: "AMBIGU", synonym: "Enigmatis, enigma", level: "Menengah" },
    { word: "AMBIGUITAS", synonym: "Makna ganda, ketidakjelasan", level: "Menengah" },
    { word: "AMBISI", synonym: "Keinginan", level: "Mudah" },
    { word: "ANALOGI", synonym: "Perbandingan", level: "Menengah" },
    { word: "ANDAL", synonym: "Kredibel", level: "Mudah" },
    { word: "ANEMIA", synonym: "Kurang darah", level: "Mudah" },
    { word: "ANGGARAN", synonym: "Catatan", level: "Mudah" },
    { word: "ANGKARA", synonym: "Kejahatan", level: "Menengah" },
    { word: "ANJUNG", synonym: "Panggung", level: "Sulit" },
    { word: "ANOMALI", synonym: "Tidak normal, menyimpang", level: "Menengah" },
    { word: "ANONIM", synonym: "Tanpa nama", level: "Mudah" },
    { word: "ANULIR", synonym: "Abolisi, penghapusan, pembatalan", level: "Sulit" },
    { word: "APATIS", synonym: "Dingin, acuh tak acuh, masa bodoh", level: "Menengah" },
    { word: "API", synonym: "Bara", level: "Mudah" },
    { word: "APORISMA", synonym: "Maksimal", level: "Sulit" },
    { word: "ARBITRER", synonym: "Acak", level: "Sulit" },
    { word: "ARISTOKRASI", synonym: "Feodal", level: "Sulit" },
    { word: "ARISTOKRAT", synonym: "Bangsawan, ningrat", level: "Menengah" },
    { word: "ARKETIPE", synonym: "Model", level: "Sulit" },
    { word: "AROGAN", synonym: "Congkak", level: "Mudah" },
    { word: "ARTIFISIAL", synonym: "Buatan", level: "Menengah" },
    { word: "ASA", synonym: "Harapan", level: "Mudah" },
    { word: "AUTENTIK", synonym: "Asli, sah, tulen, orisinil", level: "Menengah" },
    { word: "BAB", synonym: "Perkara", level: "Mudah" },
    { word: "BAGAK", synonym: "Pemberani, berani, bangga", level: "Sulit" },
    { word: "BAHANA", synonym: "Gema, dengung", level: "Sulit" },
    { word: "BAKU", synonym: "Standar, pokok, utama", level: "Mudah" },
    { word: "BALA", synonym: "Bencana", level: "Mudah" },
    { word: "BARA", synonym: "Api", level: "Mudah" },
    { word: "BENCHMARK", synonym: "Patokan, tolok ukur", level: "Menengah" },
    { word: "BERGEMING", synonym: "Diam", level: "Menengah" },
    { word: "BIBLIOGRAFI", synonym: "Daftar pustaka", level: "Menengah" },
    { word: "BIDUK", synonym: "Bahtera", level: "Sulit" },
    { word: "BLANGKO", synonym: "Abstain", level: "Menengah" },
    { word: "BOGA", synonym: "Makanan nikmat", level: "Mudah" },
    { word: "BONAFIDE", synonym: "Dapat dipercaya", level: "Menengah" },
    { word: "BONANZA", synonym: "Sumber kesenangan/kebahagiaan/kemakmuran", level: "Sulit" },
    { word: "BONUS", synonym: "Hadiah", level: "Mudah" },
    { word: "BOTANI", synonym: "Nabati", level: "Menengah" },
    { word: "BRAMACORAH", synonym: "Residivis", level: "Sulit" },
    { word: "BUBUT", synonym: "Cabut", level: "Menengah" },
    { word: "BULAT", synonym: "Bola", level: "Mudah" },
    { word: "CAGAR", synonym: "Panjar", level: "Menengah" },
    { word: "CANDU", synonym: "Adiktif", level: "Mudah" },
    { word: "CANGGIH", synonym: "Kompleks", level: "Mudah" },
    { word: "CELEPUK", synonym: "Burung hantu", level: "Sulit" },
    { word: "CENTENG", synonym: "Penjaga, bodyguard", level: "Menengah" },
    { word: "CIRI", synonym: "Karakteristik", level: "Mudah" },
    { word: "CITRA", synonym: "Gambaran", level: "Mudah" },
    { word: "CLASS", synonym: "Tingkatan", level: "Mudah" },
    { word: "COLLAPSE", synonym: "Bangkrut", level: "Menengah" },
    { word: "CONGKAK", synonym: "Sombong, arogan", level: "Mudah" },
    { word: "DAMPAK", synonym: "Hasil, Akibat", level: "Mudah" },
    { word: "DAUR", synonym: "Siklus", level: "Menengah" },
    { word: "DEDIKASI", synonym: "Pengabdian", level: "Mudah" },
    { word: "DEDUKSI", synonym: "Konklusi", level: "Sulit" },
    { word: "DEFACTO", synonym: "Secara nyata, menurut kenyataan", level: "Menengah" },
    { word: "DEFINIT", synonym: "Terbatas", level: "Sulit" },
    { word: "DEFISIT", synonym: "Kekurangan", level: "Menengah" },
    { word: "DEFLEKSI", synonym: "Penyimpangan", level: "Sulit" },
    { word: "DEGRADASI", synonym: "Kemerosotan, reduksi", level: "Menengah" },
    { word: "DEHIDRASI", synonym: "Kehilangan cairan tubuh, penyusutan air", level: "Mudah" },
    { word: "DEKADE", synonym: "Dasawarsa, sepuluh tahun", level: "Mudah" },
    { word: "DEKADENSI", synonym: "Kemerosotan (moral, akhlak)", level: "Sulit" },
    { word: "DEKRIT", synonym: "Keputusan", level: "Menengah" },
    { word: "DELIK", synonym: "Tindak pidana, pelanggaran hukum", level: "Sulit" },
    { word: "DELUSI", synonym: "Khayal, khayalan, ilusi", level: "Menengah" },
    { word: "DELUSIF", synonym: "Fiktif, palsu", level: "Menengah" },
    { word: "DENSITAS", synonym: "Kepadatan penduduk", level: "Sulit" },
    { word: "DEPENDEN", synonym: "Tergantung", level: "Menengah" },
    { word: "DEPEDENSI", synonym: "Ketergantungan", level: "Menengah" },
    { word: "DEPORTASI", synonym: "Pengusiran", level: "Menengah" },
    { word: "DEPRESI", synonym: "Stagnasi", level: "Menengah" },
    { word: "DEPUTI", synonym: "Wakil", level: "Mudah" },
    { word: "DERIVASI", synonym: "Afiksasi", level: "Sulit" },
    { word: "DESALINASI", synonym: "Penyulingan", level: "Sulit" },
    { word: "DESKRIPSI", synonym: "Pemaparan", level: "Mudah" },
    { word: "DESKRIPTIF", synonym: "Gambaran", level: "Menengah" },
    { word: "DESTRUKTIF", synonym: "Subversif", level: "Sulit" },
    { word: "DETENSI", synonym: "Penahanan", level: "Sulit" },
    { word: "DETENTE", synonym: "Rekonsiliasi", level: "Sulit" },
    { word: "DIKOTOMI", synonym: "Dua kekuatan, dibagi dua", level: "Sulit" },
    { word: "DINAMIS", synonym: "Bergerak (terus)", level: "Mudah" },
    { word: "DISPENSASI", synonym: "Pengecualian", level: "Menengah" },
    { word: "DISTORSI", synonym: "Penyimpangan", level: "Sulit" },
    { word: "DIVESTASI", synonym: "Pelepasan", level: "Sulit" },
    { word: "DOKTRIN", synonym: "Ajaran, dogma", level: "Menengah" },
    { word: "DONASI", synonym: "Bantuan", level: "Mudah" },
    { word: "DUPLIKAT", synonym: "Replika", level: "Mudah" },
    { word: "DURJANA", synonym: "Jahat", level: "Sulit" },
    { word: "EFISIEN", synonym: "Efektif", level: "Mudah" },
    { word: "EGALITER", synonym: "Sama, sederajat", level: "Sulit" },
    { word: "EGOIS", synonym: "Individualis", level: "Mudah" },
    { word: "EKAMATRA", synonym: "Fisika", level: "Sulit" },
    { word: "EKLIPS", synonym: "Gerhana", level: "Menengah" },
    { word: "EKSEKUSI", synonym: "Pelaksanaan hukuman", level: "Menengah" },
    { word: "EKSEMPLAR", synonym: "Lembar", level: "Menengah" },
    { word: "EKSENTRIK", synonym: "Aneh", level: "Menengah" },
    { word: "EKSEPSI", synonym: "Pengecualian", level: "Sulit" },
    { word: "EKSKAVASI", synonym: "Penggalian", level: "Sulit" },
    { word: "EKSODUS", synonym: "Hijrah, mengungsi, pindah", level: "Menengah" },
    { word: "EKSPANSI", synonym: "Perluasan", level: "Menengah" },
    { word: "EKSPEDISI", synonym: "Pengiriman", level: "Mudah" },
    { word: "EKSPLOITASI", synonym: "Pemanfaatan", level: "Menengah" },
    { word: "EKSPLORASI", synonym: "Pendalaman, penggalian, pengkajian", level: "Menengah" },
    { word: "EKSPRESI", synonym: "Ungkapan, roman muka", level: "Mudah" },
    { word: "EKSTENSI", synonym: "Perluasan", level: "Menengah" },
    { word: "EKSTRA", synonym: "Bonus, tambahan", level: "Mudah" },
    { word: "EKUATOR", synonym: "Khatulistiwa", level: "Menengah" },
    { word: "EKUILIBRIUM", synonym: "Keseimbangan, setimbang, sepadan", level: "Sulit" },
    { word: "EKUIVALEN", synonym: "Sama, sederajat, sebanding", level: "Sulit" },
    { word: "ELABORASI", synonym: "Penjelasan terperinci", level: "Menengah" },
    { word: "ELUSIF", synonym: "Canggih, kompleks, misterius", level: "Sulit" },
    { word: "EMBARGO", synonym: "Inhibisi, larangan", level: "Menengah" },
    { word: "EMBARKASI", synonym: "Keberangkatan", level: "Sulit" },
    { word: "ENDEMI", synonym: "Wabah, pagebluk", level: "Menengah" },
    { word: "ENIGMATIS", synonym: "Ambigu", level: "Sulit" },
    { word: "ENTITAS", synonym: "Materi, zat", level: "Sulit" },
    { word: "ENUMERASI", synonym: "Pencacahan, penghitungan", level: "Sulit" },
    { word: "EPIDEMI", synonym: "Wabah", level: "Menengah" },
    { word: "EPILOG", synonym: "Penutup", level: "Menengah" },
    { word: "ERA", synonym: "Zaman, masa", level: "Mudah" },
    { word: "ESENSI", synonym: "Hakikat", level: "Menengah" },
    { word: "ESKALASI", synonym: "Peningkatan", level: "Menengah" },
    { word: "ESTETIS", synonym: "Elok, indah", level: "Menengah" },
    { word: "ESTIMASI", synonym: "Prediksi, anggapan", level: "Menengah" },
    { word: "ESTUARI", synonym: "Muara, hilir", level: "Sulit" },
    { word: "ETIKA", synonym: "Akhlak", level: "Mudah" },
    { word: "ETNIS", synonym: "Kesukuan, rasial", level: "Mudah" },
    { word: "EUFEMISME", synonym: "Penghalusan (bahasa)", level: "Sulit" },
    { word: "EVAKUASI", synonym: "Pemindahan", level: "Mudah" },
    { word: "EVALUASI", synonym: "Penilaian", level: "Mudah" },
    { word: "EVAPORASI", synonym: "Penguapan", level: "Sulit" },
    { word: "EVOKASI", synonym: "Provokasi, sugesti, penggugah rasa", level: "Sulit" },
    { word: "EVOLUSI", synonym: "Perubahan", level: "Menengah" },
    { word: "FAKTOR", synonym: "Penyebab, unsur", level: "Mudah" },
    { word: "FAKTUAL", synonym: "Konkret, objektif", level: "Menengah" },
    { word: "FAKULTATIF", synonym: "Tidak wajib", level: "Sulit" },
    { word: "FANA", synonym: "Sementara", level: "Menengah" },
    { word: "FANTASTIS", synonym: "Luar biasa", level: "Mudah" },
    { word: "FATAMORGANA", synonym: "Halusinasi", level: "Menengah" },
    { word: "FAUNA", synonym: "Dunia hewan", level: "Mudah" },
    { word: "FENOMENA", synonym: "Gejala", level: "Mudah" },
    { word: "FEODAL", synonym: "Aristokrasi", level: "Sulit" },
    { word: "FERMENTASI", synonym: "Pembusukan", level: "Menengah" },
    { word: "FERTIL", synonym: "Subur", level: "Sulit" },
    { word: "FERTILITAS", synonym: "Kesuburan", level: "Sulit" },
    { word: "FIKSI", synonym: "Khayalan, delusi", level: "Mudah" },
    { word: "FIKTIF", synonym: "Palsu, delusif", level: "Mudah" },
    { word: "FISKAL", synonym: "Perpajakan", level: "Menengah" },
    { word: "FLEGMATIS", synonym: "Serba lamban", level: "Sulit" },
    { word: "FLORA", synonym: "Dunia tumbuhan", level: "Mudah" },
    { word: "FLUKTUATIF", synonym: "Labil", level: "Menengah" },
    { word: "FRIKSI", synonym: "Perselisihan, perpecahan, bentrokan, desakan", level: "Sulit" },
    { word: "FRONTAL", synonym: "Depan", level: "Menengah" },
    { word: "FUNGI", synonym: "Cendawan, jamur", level: "Menengah" },
    { word: "FUSI", synonym: "Penggabungan, Gabungan", level: "Sulit" },
    { word: "FUTURISTIS", synonym: "Menuju masa depan", level: "Menengah" },
    { word: "GAJI", synonym: "Honor", level: "Mudah" },
    { word: "GALAT", synonym: "Keliru, eror", level: "Menengah" },
    { word: "GALIB", synonym: "Umum", level: "Sulit" },
    { word: "GAMBARAN", synonym: "Deskriptif, imajinasi", level: "Mudah" },
    { word: "GASAL", synonym: "Ganjil", level: "Menengah" },
    { word: "GEMA", synonym: "Bahana, dengung", level: "Mudah" },
    { word: "GENERIK", synonym: "Umum, lazim", level: "Menengah" },
    { word: "GENJAH", synonym: "Cepat berbuah", level: "Sulit" },
    { word: "GLOSARIUM", synonym: "Kamus singkat/ringkas", level: "Menengah" },
    { word: "GRASI", synonym: "Pengampunan", level: "Menengah" },
    { word: "HARMONI", synonym: "Proporsi, simetri", level: "Menengah" },
    { word: "HARMONIS", synonym: "Selaras", level: "Mudah" },
    { word: "HAYATI", synonym: "Hidup", level: "Mudah" },
    { word: "HEKSAGONAL", synonym: "Segi enam", level: "Sulit" },
    { word: "HERBIVORA", synonym: "Pemakan tumbuhan", level: "Mudah" },
    { word: "HIBRIDA", synonym: "Bibit unggul", level: "Menengah" },
    { word: "HIBRIDASI", synonym: "Penyilangan", level: "Menengah" },
    { word: "HIJRAH", synonym: "Mengungsi, eksodus", level: "Menengah" },
    { word: "HIPOKRIT", synonym: "Munafik", level: "Sulit" },
    { word: "HIPOTENUSA", synonym: "Sisi miring", level: "Sulit" },
    { word: "HIPOTESIS", synonym: "Dugaan awal, anggapan dasar", level: "Menengah" },
    { word: "HOMOGEN", synonym: "Sejenis", level: "Menengah" },
    { word: "HUKUMAN", synonym: "Denda", level: "Mudah" },
    { word: "IDENTITAS", synonym: "Ciri-ciri", level: "Mudah" },
    { word: "IDEOLOGI", synonym: "Pemikiran", level: "Menengah" },
    { word: "IKEBANA", synonym: "Seni merangkai bunga", level: "Sulit" },
    { word: "IKHTIAR", synonym: "Usaha", level: "Mudah" },
    { word: "IKHTISAR", synonym: "Sinopsis, ringkasan", level: "Menengah" },
    { word: "ILUSI", synonym: "Khayalan", level: "Mudah" },
    { word: "IMAJINASI", synonym: "Gambaran", level: "Mudah" },
    { word: "IMBAS", synonym: "Efek, dampak", level: "Mudah" },
    { word: "IMITASI", synonym: "Sintesis, tiruan", level: "Mudah" },
    { word: "IMPLIKASI", synonym: "Keterkaitan", level: "Menengah" },
    { word: "IMPLISIT", synonym: "Tersirat", level: "Sulit" },
    { word: "IMPULS", synonym: "Dorongan", level: "Menengah" },
    { word: "IMUN", synonym: "Kebal", level: "Menengah" },
    { word: "INDIVIDUALIS", synonym: "Egois", level: "Menengah" },
    { word: "INDRALOKA", synonym: "Surga", level: "Sulit" },
    { word: "INFERENSI", synonym: "Deduksi, konklusi, kesimpulan, simpulan", level: "Sulit" },
    { word: "INFIKS", synonym: "Sisipan", level: "Sulit" },
    { word: "INFORMAL", synonym: "Santai", level: "Mudah" },
    { word: "INHIBISI", synonym: "Larangan, Embargo", level: "Sulit" },
    { word: "INISIASI", synonym: "Pembaiatan", level: "Menengah" },
    { word: "INJEKSI", synonym: "Suntik, suntikan", level: "Menengah" },
    { word: "INKLUSIF", synonym: "Global, termasuk, terhitung", level: "Sulit" },
    { word: "INOVASI", synonym: "Kebaruan, penemuan", level: "Menengah" },
    { word: "INSENTIF", synonym: "Bonus", level: "Menengah" },
    { word: "INSES", synonym: "Sedarah", level: "Sulit" },
    { word: "INSIDENTAL", synonym: "Tertentu, sewaktu-waktu", level: "Sulit" },
    { word: "INSINUASI", synonym: "Sindiran", level: "Sulit" },
    { word: "INSOMNIA", synonym: "Sulit/tidak bisa tidur", level: "Mudah" },
    { word: "INSPEKSI", synonym: "Peninjauan", level: "Menengah" },
    { word: "INSPIRASI", synonym: "Gagasan, ide, ilham", level: "Mudah" },
    { word: "INSTRUKSI", synonym: "Aba-aba, perintah, komando", level: "Mudah" },
    { word: "INTEGRASI", synonym: "Pembauran", level: "Menengah" },
    { word: "INTELEKTUAL", synonym: "Cendekiawan", level: "Menengah" },
    { word: "INTEROGASI", synonym: "Pemeriksaan", level: "Mudah" },
    { word: "INTERUPSI", synonym: "Penyelaan, pemotongan", level: "Menengah" },
    { word: "INTERVAL", synonym: "Sela", level: "Menengah" },
    { word: "INTERVENSI", synonym: "Campur tangan", level: "Menengah" },
    { word: "INTIMIDASI", synonym: "Menakut-nakuti", level: "Menengah" },
    { word: "INTUISI", synonym: "Naluri, insting", level: "Menengah" },
    { word: "ITERASI", synonym: "Perulangan", level: "Sulit" },
    { word: "IZIN", synonym: "Wenang", level: "Mudah" },
    { word: "JATI DIRI", synonym: "Bukti diri", level: "Mudah" },
    { word: "JURNAL", synonym: "Buletin, bacaan", level: "Menengah" },
    { word: "KAIDAH", synonym: "Ajaran", level: "Menengah" },
    { word: "KALDERA", synonym: "Kawah", level: "Sulit" },
    { word: "KALKULASI", synonym: "Perhitungan", level: "Menengah" },
    { word: "KAMPIUN", synonym: "Juara", level: "Sulit" },
    { word: "KAPITAL", synonym: "Modal", level: "Menengah" },
    { word: "KAPITALISASI", synonym: "Investasi", level: "Menengah" },
    { word: "KARAKTERISTIK", synonym: "Ciri", level: "Mudah" },
    { word: "KARNIVORA", synonym: "Pemakan daging", level: "Mudah" },
    { word: "KARTEL", synonym: "Badan usaha besar", level: "Sulit" },
    { word: "KAWAN", synonym: "Mitra", level: "Mudah" },
    { word: "KEDAP", synonym: "Rapat", level: "Menengah" },
    { word: "KELAS", synonym: "Tingkatan", level: "Mudah" },
    { word: "KELENGER", synonym: "Pingsan", level: "Menengah" },
    { word: "KHAS", synonym: "Khusus", level: "Mudah" },
    { word: "KISI-KISI", synonym: "Terali", level: "Menengah" },
    { word: "KITAB", synonym: "Buku", level: "Mudah" },
    { word: "KLAN", synonym: "Suku", level: "Mudah" },
    { word: "KLASIFIKASI", synonym: "Pengelompokan", level: "Menengah" },
    { word: "KLEPTOFOBIA", synonym: "Takut kecurian", level: "Sulit" },
    { word: "KLIMAKS", synonym: "Puncak", level: "Menengah" },
    { word: "KOGNISI", synonym: "Pemahaman", level: "Sulit" },
    { word: "KOLATERAL", synonym: "Paralel", level: "Sulit" },
    { word: "KOLEGA", synonym: "Rekan", level: "Menengah" },
    { word: "KOLONI", synonym: "Jajahan", level: "Menengah" },
    { word: "KOLUSI", synonym: "Kongkalikong", level: "Sulit" },
    { word: "KOMODITAS", synonym: "Produk", level: "Menengah" },
    { word: "KOMPLEKSITAS", synonym: "Kerumitan", level: "Menengah" },
    { word: "KOMPLEMEN", synonym: "Pelengkap", level: "Sulit" },
    { word: "KOMPOSIT", synonym: "Campuran, gabungan", level: "Sulit" },
    { word: "KOMPREHENSIF", synonym: "Luas, lengkap", level: "Sulit" },
    { word: "KONDUSIF", synonym: "Aman", level: "Menengah" },
    { word: "KONFRONTASI", synonym: "Pertikaian", level: "Menengah" },
    { word: "KONJUNGSI", synonym: "Penghubung", level: "Sulit" },
    { word: "KONKAF", synonym: "Cekung", level: "Sulit" },
    { word: "KONKLUSI", synonym: "Kesimpulan, deduksi", level: "Sulit" },
    { word: "KONKRET", synonym: "Nyata, faktual, objektif", level: "Menengah" },
    { word: "KONSESI", synonym: "Kelonggaran", level: "Sulit" },
    { word: "KONSTAN", synonym: "Kontinu", level: "Menengah" },
    { word: "KONSTITUSI", synonym: "Undang-undang", level: "Menengah" },
    { word: "KONTEMPORER", synonym: "Mutakhir, pada masa kini", level: "Sulit" },
    { word: "KONTRAS", synonym: "Perbedaan nyata", level: "Menengah" },
    { word: "KONTRIBUSI", synonym: "Bantuan, jasa", level: "Menengah" },
    { word: "KONVEKS", synonym: "Cembung", level: "Sulit" },
    { word: "KONVENSI", synonym: "Kesepakatan", level: "Sulit" },
    { word: "KONVENSIONAL", synonym: "Konservatif, kolot", level: "Menengah" },
    { word: "KONVERGEN", synonym: "Memusat", level: "Sulit" },
    { word: "KOORDINATOR", synonym: "Manajer", level: "Mudah" },
    { word: "KORELASI", synonym: "Hubungan", level: "Menengah" },
    { word: "KREDIBEL", synonym: "Andal", level: "Menengah" },
    { word: "KRONOLOGI", synonym: "Urutan peristiwa", level: "Menengah" },
    { word: "KRUSIAL", synonym: "Penting", level: "Menengah" },
    { word: "KULMINASI", synonym: "Tingkatan yang tertinggi", level: "Sulit" },
    { word: "KUOTA", synonym: "Jatah", level: "Mudah" },
    { word: "LABA", synonym: "Untung, profit", level: "Mudah" },
    { word: "LABIL", synonym: "Fluktuatif", level: "Menengah" },
    { word: "LAIK", synonym: "Layak, pantas", level: "Sulit" },
    { word: "LATEN", synonym: "Tersembunyi", level: "Sulit" },
    { word: "LATIF", synonym: "Indah", level: "Sulit" },
    { word: "LEGALITAS", synonym: "Keabsahan", level: "Menengah" },
    { word: "LEKSIKON", synonym: "Kamus, kosakata", level: "Sulit" },
    { word: "LOKA", synonym: "Tempat, dunia", level: "Sulit" },
    { word: "MAJEMUK", synonym: "Plural, heterogen", level: "Menengah" },
    { word: "MAKAR", synonym: "Akal bulus, tipu muslihat", level: "Sulit" },
    { word: "MANUSKRIP", synonym: "Dokumen, naskah", level: "Sulit" },
    { word: "MASA", synonym: "Waktu", level: "Mudah" },
    { word: "MASSIF", synonym: "Padat, pejal", level: "Menengah" },
    { word: "MATERIALISTIS", synonym: "Kebendaan", level: "Menengah" },
    { word: "MAWAS DIRI", synonym: "Introspeksi diri", level: "Menengah" },
    { word: "MAYAPADA", synonym: "Bumi, dunia", level: "Sulit" },
    { word: "MEMANGKAS", synonym: "Memotong", level: "Mudah" },
    { word: "MEMBAL", synonym: "Berbalik", level: "Menengah" },
    { word: "MEMBRAN", synonym: "Selaput", level: "Menengah" },
    { word: "METODIS", synonym: "Teratur", level: "Menengah" },
    { word: "MILITAN", synonym: "Agresif", level: "Sulit" },
    { word: "MISTIFIKASI", synonym: "Pengecohan", level: "Sulit" },
    { word: "MITRA", synonym: "Kawan", level: "Mudah" },
    { word: "MOBILITAS", synonym: "Gerak", level: "Menengah" },
    { word: "MODERAT", synonym: "Lunak, konservatif, rasional", level: "Sulit" },
    { word: "MONARKI", synonym: "Kerajaan", level: "Menengah" },
    { word: "MORBIDITAS", synonym: "Angka penduduk yang sakit dan sehat", level: "Sulit" },
    { word: "MORTALITAS", synonym: "Angka kematian", level: "Sulit" },
    { word: "MUKJIZAT", synonym: "Karamah", level: "Menengah" },
    { word: "MUTAKHIR", synonym: "Modern, terbaru", level: "Menengah" },
    { word: "MUTILASI", synonym: "Pemotongan", level: "Menengah" },
    { word: "MUTLAK", synonym: "Absolut", level: "Menengah" },
    { word: "NABATI", synonym: "Botani", level: "Menengah" },
    { word: "NALURI", synonym: "Insting, Intuisi", level: "Mudah" },
    { word: "NANAR", synonym: "Bingung", level: "Sulit" },
    { word: "NARASI", synonym: "Deskripsi", level: "Menengah" },
    { word: "NARATIF", synonym: "Deskriptif", level: "Menengah" },
    { word: "NATALITAS", synonym: "Angka kelahiran", level: "Sulit" },
    { word: "NAVIGASI", synonym: "Pelayaran, penerbangan", level: "Menengah" },
    { word: "NEGOSIASI", synonym: "Perundingan", level: "Mudah" },
    { word: "NISBI", synonym: "Relatif", level: "Sulit" },
    { word: "NOMADEN", synonym: "Berpindah-pindah", level: "Menengah" },
    { word: "NOMENKLATUR", synonym: "Tata nama", level: "Sulit" },
    { word: "NOTULEN", synonym: "Catatan, risalah", level: "Menengah" },
    { word: "NUANSA", synonym: "Perbedaan makna", level: "Menengah" },
    { word: "OBJEKTIF", synonym: "Ilmiah", level: "Mudah" },
    { word: "OKTAGON", synonym: "Segi delapan", level: "Sulit" },
    { word: "OMNIVORA", synonym: "Pemakan segala (tumbuhan dan daging)", level: "Menengah" },
    { word: "OPAS", synonym: "Sekuriti", level: "Sulit" },
    { word: "ORIGAMI", synonym: "Seni melipat kertas", level: "Menengah" },
    { word: "ORISINIL", synonym: "Asli, autentik", level: "Mudah" },
    { word: "OTODIDAK", synonym: "Belajar sendiri", level: "Menengah" },
    { word: "OTORITAS", synonym: "Dominasi", level: "Menengah" },
    { word: "OUT OF DATE", synonym: "Kedaluwarsa", level: "Mudah" },
    { word: "PAGU", synonym: "Plafon", level: "Sulit" },
    { word: "PANDIR", synonym: "Bodoh, dungu, bebal", level: "Sulit" },
    { word: "PANORAMA", synonym: "Pemandangan", level: "Mudah" },
    { word: "PARADIGMA", synonym: "Model, pola, kerangka berpikir", level: "Sulit" },
    { word: "PARADOKS", synonym: "Bertentangan", level: "Sulit" },
    { word: "PARADOKSAL", synonym: "Kontras", level: "Sulit" },
    { word: "PARALEL", synonym: "Sejajar", level: "Menengah" },
    { word: "PARAMETER", synonym: "Standar ukuran", level: "Menengah" },
    { word: "PARIPURNA", synonym: "Sempurna, lengkap", level: "Sulit" },
    { word: "PARTIKELIR", synonym: "Swasta", level: "Sulit" },
    { word: "PASCA", synonym: "Sesudah", level: "Mudah" },
    { word: "PATOLOGI", synonym: "Ilmu tentang penyakit", level: "Sulit" },
    { word: "PEDAGOGI", synonym: "Pengajaran, pendidikan", level: "Sulit" },
    { word: "PEJAL", synonym: "Padat", level: "Sulit" },
    { word: "PENTAGON", synonym: "Segi lima", level: "Menengah" },
    { word: "PERLENTE", synonym: "Gagah", level: "Sulit" },
    { word: "PERMISIF", synonym: "Liberal, terbuka", level: "Sulit" },
    { word: "PERSUASI", synonym: "Agitasi, ajakan", level: "Menengah" },
    { word: "PETISI", synonym: "Gugatan", level: "Menengah" },
    { word: "PIONIR", synonym: "Pelopor, perintis", level: "Menengah" },
    { word: "POLEMIK", synonym: "Kontroversi", level: "Menengah" },
    { word: "PORTO", synonym: "Biaya", level: "Sulit" },
    { word: "PRA", synonym: "Sebelum", level: "Mudah" },
    { word: "PREFIKS", synonym: "Awalan", level: "Sulit" },
    { word: "PREMI", synonym: "Uang hadiah", level: "Menengah" },
    { word: "PREPOSISI", synonym: "Kata depan", level: "Sulit" },
    { word: "PRESENSI", synonym: "Keberadaan", level: "Menengah" },
    { word: "PREVENTIF", synonym: "Defensif", level: "Menengah" },
    { word: "PRIMER", synonym: "Utama, pokok", level: "Mudah" },
    { word: "PROFIT", synonym: "Keuntungan", level: "Mudah" },
    { word: "PROHIBISI", synonym: "Larangan", level: "Sulit" },
    { word: "PROLETAR", synonym: "Rakyat jelata", level: "Sulit" },
    { word: "PROLOG", synonym: "Pembuka", level: "Menengah" },
    { word: "PROMINEN", synonym: "Terkenal, terkemuka", level: "Sulit" },
    { word: "PROMOSI", synonym: "Pemasaran", level: "Mudah" },
    { word: "PROMOVENDUS", synonym: "Calon doktor", level: "Sulit" },
    { word: "PROPAGANDA", synonym: "Ajakan, kampanye", level: "Menengah" },
    { word: "PROPORSI", synonym: "Nisbah, perbandingan", level: "Menengah" },
    { word: "PROTEKSI", synonym: "Perlindungan", level: "Menengah" },
    { word: "PROTESIS", synonym: "Imitasi", level: "Sulit" },
    { word: "PROVOKASI", synonym: "Gangguan, sugesti, evokasi, pancingan", level: "Sulit" },
    { word: "PRUDENSIAL", synonym: "Bijaksana", level: "Sulit" },
    { word: "RABAT", synonym: "Potongan harga, diskon", level: "Sulit" },
    { word: "RANCU", synonym: "Kacau", level: "Menengah" },
    { word: "RANDOM", synonym: "Acak", level: "Mudah" },
    { word: "REBOISASI", synonym: "Penghijauan", level: "Menengah" },
    { word: "REFERENSI", synonym: "Rujukan", level: "Mudah" },
    { word: "REFLEKSI", synonym: "Pencerminan/pemantulan", level: "Menengah" },
    { word: "REGISTRASI", synonym: "Pendaftaran", level: "Mudah" },
    { word: "REHABILITASI", synonym: "Perbaikan", level: "Menengah" },
    { word: "REKLAMASI", synonym: "Penimbunan", level: "Menengah" },
    { word: "REKONSILIASI", synonym: "Perdamaian", level: "Sulit" },
    { word: "RELATIF", synonym: "Nisbi", level: "Menengah" },
    { word: "REMISI", synonym: "Pengampunan, pengurangan hukuman", level: "Menengah" },
    { word: "RENDEZVOUS", synonym: "Pertemuan", level: "Sulit" },
    { word: "REPLIKA", synonym: "Duplikat, tiruan", level: "Menengah" },
    { word: "REPORTASE", synonym: "Peliputan, pemberitaan", level: "Menengah" },
    { word: "RESESI", synonym: "Stagnasi, masa sulit", level: "Menengah" },
    { word: "RESIDU", synonym: "Sisa", level: "Sulit" },
    { word: "RESISTAN", synonym: "Kuat, tangguh", level: "Sulit" },
    { word: "RESTRIKSI", synonym: "Pembatasan", level: "Sulit" },
    { word: "REVOLUSI", synonym: "Perubahan", level: "Mudah" },
    { word: "RIGID", synonym: "Kaku", level: "Sulit" },
    { word: "RINGKIH", synonym: "Rapuh", level: "Menengah" },
    { word: "SAIS", synonym: "Kusir", level: "Sulit" },
    { word: "SAKSAMA", synonym: "Cermat", level: "Menengah" },
    { word: "SANGKUR", synonym: "Bayonet", level: "Sulit" },
    { word: "SEDIMENTASI", synonym: "Pengendapan", level: "Menengah" },
    { word: "SEKTE", synonym: "Aliran, mazhab", level: "Sulit" },
    { word: "SELEBRASI", synonym: "Perayaan", level: "Menengah" },
    { word: "SEMENJANA", synonym: "Sedang", level: "Sulit" },
    { word: "SEREBRUM", synonym: "Otak besar", level: "Sulit" },
    { word: "SEREMONI", synonym: "Upacara", level: "Menengah" },
    { word: "SIKLUS", synonym: "Daur", level: "Menengah" },
    { word: "SINE QUA NON", synonym: "Harus ada", level: "Sulit" },
    { word: "SINGULAR", synonym: "Tunggal", level: "Sulit" },
    { word: "SINOPSIS", synonym: "Ikhtisar, intisari", level: "Menengah" },
    { word: "SINTESIS", synonym: "Imitasi, buatan", level: "Sulit" },
    { word: "SINYALEMEN", synonym: "Petunjuk", level: "Sulit" },
    { word: "SKEPTIS", synonym: "Ragu-ragu", level: "Sulit" },
    { word: "SPESIFIK", synonym: "Istimewa", level: "Menengah" },
    { word: "SPIRITUAL", synonym: "Kerohanian, psikis", level: "Menengah" },
    { word: "SPORADIS", synonym: "Kadang-kadang, jarang", level: "Sulit" },
    { word: "STAGNASI", synonym: "Depresi, macet", level: "Sulit" },
    { word: "STATIS", synonym: "Diam", level: "Menengah" },
    { word: "STIGMA", synonym: "Ciri negatif", level: "Sulit" },
    { word: "SUAR", synonym: "Nyala api", level: "Sulit" },
    { word: "SUBSTANSI", synonym: "Intisari", level: "Menengah" },
    { word: "SUBVERSIF", synonym: "Destruktif", level: "Sulit" },
    { word: "SUFIKS", synonym: "Akhiran", level: "Sulit" },
    { word: "SUKSESI", synonym: "Pergantian pemimpin", level: "Sulit" },
    { word: "SUMBANG", synonym: "Tidak selaras", level: "Menengah" },
    { word: "SUPERVISI", synonym: "Pengawasan", level: "Menengah" },
    { word: "SUPREMASI", synonym: "Kekuasaan tertinggi", level: "Sulit" },
    { word: "SWASEMBADA", synonym: "Mandiri, independen, otonom", level: "Menengah" },
    { word: "SWATANTRA", synonym: "Otonomi", level: "Sulit" },
    { word: "TAG", synonym: "Label", level: "Mudah" },
    { word: "TANGGALKAN", synonym: "Lepaskan", level: "Menengah" },
    { word: "TANGKAL", synonym: "Cegah", level: "Menengah" },
    { word: "TANGSI", synonym: "Barak", level: "Sulit" },
    { word: "TANUR", synonym: "Perapian", level: "Sulit" },
    { word: "TAUTOLOGI", synonym: "Repetisi", level: "Sulit" },
    { word: "TENDENSI", synonym: "Cenderung, kecenderungan", level: "Sulit" },
    { word: "TENTATIF", synonym: "Belum pasti", level: "Sulit" },
    { word: "TERA", synonym: "Stempel", level: "Sulit" },
    { word: "TERALI", synonym: "Kisi-kisi", level: "Sulit" },
    { word: "TERITORI", synonym: "Zona", level: "Menengah" },
    { word: "TERMAKTUB", synonym: "Tercatat", level: "Sulit" },
    { word: "TOLAN", synonym: "Sahabat", level: "Sulit" },
    { word: "TRANSEDENTAL", synonym: "Abstrak, sulit dipahami", level: "Sulit" },
    { word: "TRANSISI", synonym: "Peralihan", level: "Menengah" },
    { word: "TUNAAKSARA", synonym: "Buta huruf", level: "Menengah" },
    { word: "TUNADAKSA", synonym: "Cacat tubuh", level: "Menengah" },
    { word: "TUNAGRAHITA", synonym: "Cacat mental/pikiran", level: "Sulit" },
    { word: "TUNANETRA", synonym: "Buta", level: "Menengah" },
    { word: "TUNARUNGU", synonym: "Tuli", level: "Menengah" },
    { word: "TUNASUSILA", synonym: "Pelacur", level: "Sulit" },
    { word: "TUNAWICARA", synonym: "Bisu", level: "Menengah" },
    { word: "TUNAWISMA", synonym: "Gelandangan", level: "Menengah" },
    { word: "TUSLAH", synonym: "Tambah", level: "Sulit" },
    { word: "UGAHARI", synonym: "Sedang, pertengahan, sederhana", level: "Sulit" },
    { word: "UP TO DATE", synonym: "Baru", level: "Mudah" },
    { word: "UTOPIS", synonym: "Bersifat khayal", level: "Sulit" },
    { word: "VADEMEKUM", synonym: "Kamus kecil", level: "Sulit" },
    { word: "VAKANSI", synonym: "Liburan", level: "Sulit" },
    { word: "VALIDITAS", synonym: "Kebenaran", level: "Menengah" },
    { word: "VANDALISME", synonym: "Destruksi, perusakan", level: "Menengah" },
    { word: "VEGETASI", synonym: "Tumbuh-tumbuhan", level: "Mudah" },
    { word: "VERSUS", synonym: "Lawan", level: "Mudah" },
    { word: "VIRTUAL", synonym: "Impian", level: "Menengah" },
    { word: "VIRULEN", synonym: "Jahat, busuk, keji", level: "Sulit" },
    { word: "VISUAL", synonym: "Optis", level: "Mudah" },
    { word: "VITAL", synonym: "Esensial, fundamental", level: "Menengah" },
    { word: "VOLUNTER", synonym: "Sukarelawan", level: "Menengah" },
    { word: "WARISAN", synonym: "Harta benda", level: "Mudah" },
    { word: "WARKAT", synonym: "Surat", level: "Sulit" },
    { word: "WENANG", synonym: "Izin", level: "Menengah" },
    { word: "YURISDIKSI", synonym: "Kekuasaan", level: "Sulit" },
    { word: "ZENIT", synonym: "Puncak, titik puncak", level: "Sulit" }
];
